### ISSUE TITLE
Qiskit BackendV1 is deprecated in Qiskit 1.2

### ISSUE THREAD

**Issue by marcosdiezgarcia** [Fujitsu-UTokyo-QDD/QDD#69]
The main class [`QddBackend`](https://github.com/Fujitsu-UTokyo-QDD/QDD/blob/9d5aa966ddcea71c67d6ac8131faf47e87989d72/qdd/qdd_backend.py#L122C18-L122C27) inherits from Qiskit's [`BackendV1`](https://docs.quantum.ibm.com/api/qiskit/qiskit.providers.BackendV1). However, BackendV1 is deprecated since Qiskit version 1.2 and will be removed in Qiskit 2.0. Qiskit suggests to migrate from BackendV1 to BackendV2.

**Comment by kkyusuke** [comment]
Thanks for the kind reminder of the deprecations.
Actually, we are working on supporting v2 classes, and it will come shortly.
Please wait for a while.
